# .github/workflows/build.yml
# V14: The Simple, Correct Solution - Explicitly specifying the Gradle version.

name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # This line tells the action to use a specific Gradle version,
          # bypassing the need for a local gradlew file. This is the fix.
          gradle-version: '8.4'
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signal-intel-apk
          path: app/build/outputs/apk/debug/app-debug.apk
