# .github/workflows/build.yml
# V11: The Correct Approach - Building a native Android app with Gradle.

name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        run: |
          # The standard command to build a native Android app
          chmod +x gradlew
          ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signal-intel-apk
          path: app/build/outputs/apk/debug/app-debug.apk
