# .github/workflows/build.yml
# V13: The Correct, Modern Native Build - Using the official Gradle Build Action.

name: Build Android APK

on: [push]

jobs S:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signal-intel-apk
          path: app/build/outputs/apk/debug/app-debug.apk
